name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: List repo files
        run: ls -R

      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_PRIVATE_KEY }}" > ~/.ssh/meinPrivateKey
          chmod 600 ~/.ssh/meinPrivateKey
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Create folder on EC2
        run: ssh -i ~/.ssh/meinPrivateKey ubuntu@${{ secrets.EC2_IP }} "mkdir -p ~/Aufgabeworkflowdocker"

      - name: Copy file to EC2
        run: scp -i ~/.ssh/meinPrivateKey Aufgabeworkflowdocker/info.txt ubuntu@${{ secrets.EC2_IP }}:~/Aufgabeworkflowdocker/info.txt

      - name: Optional check
        run: ssh -i ~/.ssh/meinPrivateKey ubuntu@${{ secrets.EC2_IP }} "ls -l ~/Aufgabeworkflowdocker && head -n 1 ~/Aufgabeworkflowdocker/info.txt"
